version: '3.8'

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log
  
  mariadb:
    driver: local

networks:
  iot:
    name: iot_host
    driver: bridge

services:
  
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER:  ${MARIADB_USER} 
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "4000:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      iot:
        aliases: 
          - mariadb_host

  phpmyadmin:
    depends_on:
      - mariadb
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    expose:
      - "4001"
    ports:
      - "4001:80"
    environment:
      - PMA_HOST=mariadb_host
      - PMA_PORT=3306 
    networks:
      iot:
        aliases: 
          - phpmyadmin_host
  emqx:
    depends_on:
      - mariadb
    container_name: emqx
    image: emqx/emqx:4.4.14
    restart: always

    ports:
      - 18083:18083
      - 18084:18084
      - 1883:1883
      - 8883:8883
      - 8073:8083
      - 8074:8084

    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
 
    environment:
      EMQX_NAME: iothost-org
      EMQX_HOST: 127.0.0.1

      ## Value: String
      # dashboard.default_user.password = public
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "emqxpass"

      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"
      # Configurar pluguins reglas acl
      # etc/plugins/emqx_auth_mysql.conf
      #auth.mysql.server = 127.0.0.1:3306
      EMQX_AUTH__MYSQL__SERVER: "mariadb_host:3306" 
      #auth.mysql.username = emqx
      EMQX_AUTH__MYSQL__USERNAME: ${MARIADB_USER} 
      #auth.mysql.password = public
      EMQX_AUTH__MYSQL__PASSWORD: ${MARIADB_PASSWORD} 
      #auth.mysql.database = mqtt
      EMQX_AUTH__MYSQL__DATABASE: ${MARIADB_DATABASE} 

      #dashboard.listener.https = 18084
      EMQX_DASHBOARD__LISTENER__HTTPS: 18084
      #dashboard.listener.https.acceptors = 2
      EMQX_DASHBOARD__LISTENER__HTTPS__ACCEPTORS: 2
      #dashboard.listener.https.max_clients = 512
      EMQX_DASHBOARD__LISTENER__HTTPS__MAX_CLIENTS: 2
      #dashboard.listener.https.keyfile = etc/certs/key.pem
      EMQX_DASHBOARD__LISTENER__HTTPS__KEYFILE: "etc/certs/key.pem"
      #dashboard.listener.https.certfile = etc/certs/cert.pem
      EMQX_DASHBOARD__LISTENER__HTTPS__CERTFILE: "etc/certs/cert.pem"

      #dashboard.listener.http.max_clients = 512 - 18083 - 2
      EMQX_DASHBOARD__LISTENER__HTTP__MAX_CLIENTS: 2

      #management.listener.https = 8081
      EMQX_MANAGEMENT__LISTENER_HTTPS: 8082
      #management.listener.https.acceptors = 2
      EMQX_MANAGEMENT__LISTENER_HTTPS__ACCEPTORS: 2
      #management.listener.https.max_clients = 512
      EMQX_MANAGEMENT__LISTENER_HTTPS__MAX_CLIENTS: 2
      #management.listener.https.backlog = 512
      EMQX_MANAGEMENT__LISTENER_HTTPS__BACKLOG: 2
      #management.listener.https.send_timeout = 15s
      EMQX_MANAGEMENT__LISTENER_HTTPS__SEND_TIMEOUT: "15s"
      #management.listener.https.send_timeout_close = on
      EMQX_MANAGEMENT__LISTENER_HTTPS__SEND__TIMEOUT_CLOSE: "on"
      #management.listener.https.certfile = etc/certs/cert.pem
      EMQX_MANAGEMENT__LISTENER_HTTPS__CERTFILE: "etc/certs/cert.pem"
      #management.listener.https.keyfile = etc/certs/key.pem
      EMQX_MANAGEMENT__LISTENER_HTTPS__KEYFILE: "etc/certs/key.pem"

      #listener.tcp.external.max_connections = 1024000 Puerto 1883
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
      #listener.ssl.external.max_connections = 102400 Puerto 8883
      EMQX_LISTENER__SSL__EXTERNAL__MAX_CONNECTIONS: 1000
      #listener.ws.external.max_connections = 102400 Puerto 8083
      EMQX_LISTENER__WS__EXTERNAL__MAX_CONNECTIONS: 1000
      #listener.wss.external.max_connections = 102400 Puerto 8084
      EMQX_LISTENER__WSS__EXTERNAL__MAX_CONNECTIONS: 1000

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mysql"
    
    networks:
      iot:
        aliases:
          - emqx_host

    


